# roles/tomcat/tasks/main.yml
- name: Create tomcat group
  group:
    name: tomcat
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    group: tomcat
    shell: /bin/false
    home: /opt/tomcat

- name: Download Tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
    dest: /tmp/tomcat.tar.gz

- name: Create tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract tomcat
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Set permissions
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Copy systemd service
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service

- name: Reload systemd
  shell: systemctl daemon-reload

- name: Start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
