plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  tag:Environment: dev
  tag:Role: app
  instance-state-name: running

hostnames:
  - instance-id

compose:
  ansible_host: instance_id
  ansible_connection: "'aws_ssm'"
  ansible_aws_ssm_bucket_name: '"votingapp-tf-state-dev-123456"'
  ansible_aws_ssm_region: '"us-east-1"'
