- name: Bootstrap servers
  hosts: aws_ec2
  gather_facts: false
  become: true
  tags: bootstrap

  roles:
    - bootstrap

- name: Configure application servers
  hosts: aws_ec2
  gather_facts: true
  become: true
  roles:
    - { role: common, tags: common }
    - { role: java, tags: java }
    - { role: tomcat, tags: tomcat }
